#!/bin/bash

# common paths
BLENDER=$(pwd)/blender/blender
VIDEO_DIR="/mnt/d/OneDrive/Titans Of Eden/videos"
RENDER_DIR="/mnt/d/vframe"
export UPLOAD_DIR="/mnt/d/OneDrive/Titans Of Eden/website/vid"

# animate videos directly
for FILE in \
    "Landing/G - Temples/60-Sec Temples.blend" \
; do
    IFNAME=$(basename "$FILE")
    OFNAME=$RENDER_DIR/${IFNAME%.*}
    $BLENDER -b "$VIDEO_DIR/$FILE" --render-output "$OFNAME" -s 630 -e 780 -a
done

# animate videos using python script
for FILE in \
    "Landing/A - Opening/60-Sec Opening.blend" \
    "Landing/B - Haunt/60-Sec Haunt.blend" \
    "Landing/C - Subvert/60-Sec Subvert.blend" \
    "Landing/D - No Wait/60-Sec No Wait.blend" \
    "Landing/E - Classic/60-Sec Classic.blend" \
    "Landing/F - Constructed/60-Sec Constructed.blend" \
    "Landing/G - Temples/60-Sec Temples.blend" \
    "Empire/anim/Empire Anim.blend" \
    "No-Wait/anim/No-Wait Anim.blend" \
    "Constructed/anim/Constructed Anim.blend" \
; do
    IFNAME=$(basename "$FILE")
    OFNAME=$RENDER_DIR/${IFNAME%.*}
    $BLENDER -b "$VIDEO_DIR/$FILE" --render-output "$OFNAME" -P skip_still.py
done

# render videos
for FILE in \
    "Card Flip.blend" \
    "Title Card/Storm Title.blend" \
    "Title Card/Fire Title.blend" \
    "Title Card/Ice Title.blend" \
    "Title Card/Stone Title.blend" \
    "Title Card/Stone Title.blend" \
    "Title Card/Title.blend" \
    "Title Card/Title Video.blend" \
    "Landing/Landing Video.blend" \
    "Empire/Empire Video.blend" \
    "No-Wait/No-Wait Video.blend" \
    "Constructed/Constructed Video.blend" \
; do

    # get output fname
    IFNAME=$(basename "$FILE")
    OFNAME="$RENDER_DIR/${IFNAME%.*}"
    if [ ! -z "$(echo $FILE | grep Video)" ]; then
        OFNAME="${OFNAME}.mkv"
    fi 

    # render video
    $BLENDER -b "$VIDEO_DIR/$FILE" --render-output "$OFNAME" -a
done

# convert videos, move to website directory
for IFNAME in $RENDER_DIR/*.mkv; do
    OFNAME=$UPLOAD_DIR/$( \
        basename "$IFNAME" \
        | sed 's/ /_/g' \
        | sed 's/-//g' \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/.mkv//g' \
    )
    H264="${OFNAME}".h264.mp4
    H265="${OFNAME}".h265.mp4
    WEBM="${OFNAME}".webm
    ffmpeg -y -i "$IFNAME" -c:v libx264 -c:a aac "$H264"
    ffmpeg -y -i "$H264" -c:v libx265 -vtag hvc1 "$H265"
    ffmpeg -y -i "$H264" -c:v libvpx-vp9 -b:v 0 -crf 50 -pass 1 -an -f null /dev/null
    ffmpeg -y -i "$H264" -c:v libvpx-vp9 -b:v 0 -crf 50 -pass 2 -c:a libopus "$WEBM"
done

# make short clips (former gifs)
python3 make_clips.py

# upload videos
cd "$UPLOAD_DIR"
./upload
