#!/bin/bash

# common paths
BLENDER=$(pwd)/blender/blender
VIDEO_DIR="/mnt/d/OneDrive/Titans Of Eden/videos"
RENDER_DIR="/mnt/d/vframe"
export UPLOAD_DIR="/mnt/d/OneDrive/Titans Of Eden/website/vid"

# animate videos directly
for FILE in \
    "Landing/G - Temples/60-Sec Temples.blend" \
; do
    IFNAME=$(basename "$FILE")
    OFNAME=$RENDER_DIR/${IFNAME%.*}
    $BLENDER -b "$VIDEO_DIR/$FILE" --render-output "$OFNAME" -s 630 -e 780 -a
done

# animate videos using python script
for FILE in \
    "Landing/A - Opening/60-Sec Opening.blend" \
    "Landing/B - Haunt/60-Sec Haunt.blend" \
    "Landing/C - Subvert/60-Sec Subvert.blend" \
    "Landing/D - No Wait/60-Sec No Wait.blend" \
    "Landing/E - Classic/60-Sec Classic.blend" \
    "Landing/F - Constructed/60-Sec Constructed.blend" \
    "Landing/G - Temples/60-Sec Temples.blend" \
    "Empire/anim/Empire Anim.blend" \
    "No-Wait/anim/No-Wait Anim.blend" \
    "Constructed/anim/Constructed Anim.blend" \
; do
    IFNAME=$(basename "$FILE")
    OFNAME=$RENDER_DIR/${IFNAME%.*}
    $BLENDER -b "$VIDEO_DIR/$FILE" --render-output "$OFNAME" -P skip_still.py
done

# render videos
for FILE in \
    "Card Flip.blend" \
    "Title Card/Storm Title.blend" \
    "Title Card/Fire Title.blend" \
    "Title Card/Ice Title.blend" \
    "Title Card/Stone Title.blend" \
    "Title Card/Stone Title.blend" \
    "Title Card/Title.blend" \
    "Title Card/Title Video.blend" \
    "Landing/Landing Video.blend" \
    "Empire/Empire Video.blend" \
    "No-Wait/No-Wait Video.blend" \
    "Constructed/Constructed Video.blend" \
; do

    # get output fname
    IFNAME=$(basename "$FILE")
    OFNAME=$RENDER_DIR/${IFNAME%.*}

    # render video
    $BLENDER -b "$VIDEO_DIR/$FILE" --render-output "$OFNAME" -a

    # renumber title video
    if [ "$IFNAME" == "Title.blend" ]; then
        python3 renumber.py
    fi

    # delete existing (old) video
    rm -f "$OFNAME.mkv"

    # remove numbers from video filename
    ACTUAL_OFNAME=$(ls "$OFNAME"* | grep .mkv)
    if [ ! -z "$ACTUAL_OFNAME" ]; then
        TARGET_OFNAME=$(echo $ACTUAL_OFNAME | sed -E 's/[0-9]{4}-[0-9]{4}//g')
        mv "$ACTUAL_OFNAME" "$TARGET_OFNAME"
    fi
done

# convert to mp4, move to website directory
for IFNAME in $RENDER_DIR/*.mkv; do
    OFNAME=$( \
        basename "$IFNAME" \
        | sed 's/ /_/g' \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/.mkv/.mp4/g' \
    )
    ffmpeg -i "$IFNAME" -y -codec copy "$UPLOAD_DIR/$OFNAME"
done

# make short clips (former gifs)
python3 make_clips.py

# upload videos
cd "$UPLOAD_DIR"
./upload
